services:
  app:
    build:
      context: .
    ports:
      - "8080:8000"
      - "9229:9229"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - APP_ENV=development